/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng nhập bằng tài khoản `users` (bcrypt) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đổi refresh token lấy cặp token mới (xoay vòng refresh token) */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thu hồi refresh token (cả chuỗi xoay vòng) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Người dùng hiện tại + phạm vi dữ liệu */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/filters/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tài khoản trong phạm vi người dùng (cho bộ lọc) */
        get: operations["listFilterAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/filters/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chiến dịch có link thuộc phạm vi người dùng */
        get: operations["listFilterCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/filters/prefixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Danh sách prefix (`sale`, `lm`, …) */
        get: operations["listFilterPrefixes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R1 — Tổng quan (KPI, timeline, top, phân rã, heatmap) theo phạm vi */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R2 — Danh sách tài khoản kèm chỉ số */
        get: operations["listAccountReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/accounts/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R2 — Chi tiết tài khoản */
        get: operations["getAccountReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R3 — Danh sách chiến dịch kèm chỉ số */
        get: operations["listCampaignReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/campaigns/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R3 — So sánh 2–5 chiến dịch */
        get: operations["compareCampaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/campaigns/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R3 — Chi tiết chiến dịch */
        get: operations["getCampaignReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/ctvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R4 — Bảng xếp hạng CTV (không gồm "chưa định danh") */
        get: operations["listCtvReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/ctvs/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R4 — Tra cứu CTV theo SĐT (mọi định dạng) / hash — khớp chính xác qua index ctv_id */
        get: operations["lookupCtv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/ctvs/unidentified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R4 — Link / click chưa định danh CTV (admin, chính chủ) */
        get: operations["getUnidentifiedCtv"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/ctvs/{ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R4 — Chi tiết CTV (ref = ctv_ref mờ, không phải SĐT) */
        get: operations["getCtvReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/links/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R5 — Top link theo click / tăng trưởng; link "chết" (không click N ngày) */
        get: operations["listTopLinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/links/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R5 — Chi tiết link (KPI, timeline, phân rã, 100 click gần nhất) */
        get: operations["getLinkReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/links/{code}/qrcode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mã QR của short URL (PNG) */
        get: operations["getLinkQrcode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/clicks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R6 — Nhật ký click thô (≤ 3 tháng), phân trang con trỏ; IP che theo vai trò */
        get: operations["listClicks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/clicks/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** R6b — Click Explorer — lọc nhiều tiêu chí, nhóm theo 1–3 chiều, top N + "khác", so kỳ trước */
        post: operations["queryClicks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/clicks/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** R6b — Giá trị cho bộ lọc (theo phạm vi); field=param.<key> cho tham số URL */
        get: operations["getClickFacets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/params": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** §4.1 c2 — Tham số URL đang theo dõi kèm số giá trị, số link, tổng click */
        get: operations["listParamReports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/params/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** §4.1 c2 — Giá trị của một tham số + chỉ số, timeline top 5, cảnh báo dữ liệu */
        get: operations["getParamReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Báo cáo / bộ lọc đã lưu của tôi */
        get: operations["listSavedReports"];
        put?: never;
        post: operations["createSavedReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-reports/shared/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mở báo cáo được chia sẻ — người nhận chỉ thấy dữ liệu thuộc phạm vi của mình khi chạy */
        get: operations["getSharedReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSavedReport"];
        put?: never;
        post?: never;
        delete: operations["deleteSavedReport"];
        options?: never;
        head?: never;
        patch: operations["updateSavedReport"];
        trace?: never;
    };
    "/v1/saved-reports/{id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bật / tắt chia sẻ qua link */
        post: operations["shareSavedReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @example about:blank */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Mã lỗi máy đọc được (vd `invalid_credentials`, `account_locked`, `forbidden_scope`) */
            code?: string;
            request_id?: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
        /** @enum {string} */
        Role: "admin" | "user" | "viewer";
        /**
         * @default day
         * @enum {string}
         */
        Granularity: "day" | "week" | "month";
        /**
         * @default desc
         * @enum {string}
         */
        SortOrder: "asc" | "desc";
        LoginRequest: {
            username: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        TokenPair: {
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
            user: components["schemas"]["Me"];
        };
        Me: {
            username: string;
            email?: string;
            role: components["schemas"]["Role"];
            /** @description true = thấy toàn bộ tài khoản (admin) */
            all_accounts: boolean;
            /** @description Tài khoản được xem khi `all_accounts = false` */
            accounts: string[];
        };
        AccountOption: {
            username: string;
        };
        AccountOptionList: {
            items: components["schemas"]["AccountOption"][];
        };
        CampaignOption: {
            code: string;
            name: string;
        };
        CampaignOptionList: {
            items: components["schemas"]["CampaignOption"][];
        };
        PrefixOption: {
            id: string;
            is_default: boolean;
            description?: string;
        };
        PrefixOptionList: {
            items: components["schemas"]["PrefixOption"][];
        };
        /** @description Chỉ số theo định nghĩa PLAN_SERVICE_API.md §5.2 */
        Metrics: {
            /**
             * Format: int64
             * @description Link chưa xoá tạo đến hết kỳ
             */
            total_links?: number;
            /** Format: int64 */
            new_links: number;
            /**
             * Format: int64
             * @description Số link có ≥ 1 click (không tính bot) trong kỳ
             */
            active_links: number;
            /**
             * Format: int64
             * @description Lượt redirect thành công, không tính bot
             */
            clicks: number;
            /** Format: int64 */
            unique_clicks: number;
            /** Format: int64 */
            bot_clicks: number;
            /** Format: int64 */
            suspicious_clicks: number;
            /**
             * Format: double
             * @description clicks / active_links
             */
            ctr_per_link: number;
        };
        /** @description Tỉ lệ thay đổi so kỳ trước (0.25 = +25%); null khi kỳ trước = 0 */
        MetricChanges: {
            /** Format: double */
            total_links?: number | null;
            /** Format: double */
            new_links?: number | null;
            /** Format: double */
            active_links?: number | null;
            /** Format: double */
            clicks?: number | null;
            /** Format: double */
            unique_clicks?: number | null;
            /** Format: double */
            bot_clicks?: number | null;
            /** Format: double */
            suspicious_clicks?: number | null;
            /** Format: double */
            ctr_per_link?: number | null;
        };
        Period: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
        Kpis: {
            period: components["schemas"]["Period"];
            current: components["schemas"]["Metrics"];
            previous_period?: components["schemas"]["Period"];
            previous?: components["schemas"]["Metrics"];
            change?: components["schemas"]["MetricChanges"];
        };
        SeriesPoint: {
            /**
             * Format: date
             * @description Ngày đầu của bucket (ngày / thứ Hai của tuần / ngày 1 của tháng)
             */
            period: string;
            /** Format: int64 */
            clicks: number;
            /** Format: int64 */
            unique_clicks: number;
            /** Format: int64 */
            bot_clicks: number;
            /** Format: int64 */
            new_links: number;
            /** Format: int64 */
            active_links: number;
        };
        Series: {
            granularity: components["schemas"]["Granularity"];
            points: components["schemas"]["SeriesPoint"][];
            /** @description Kỳ trước, cùng số bucket, căn theo thứ tự */
            previous?: components["schemas"]["SeriesPoint"][];
        };
        BreakdownItem: {
            key: string;
            /** Format: int64 */
            clicks: number;
            /**
             * Format: double
             * @description Tỉ trọng trên tổng click
             */
            share: number;
        };
        Breakdowns: {
            device: components["schemas"]["BreakdownItem"][];
            os: components["schemas"]["BreakdownItem"][];
            browser: components["schemas"]["BreakdownItem"][];
            source_group: components["schemas"]["BreakdownItem"][];
            referer: components["schemas"]["BreakdownItem"][];
            country: components["schemas"]["BreakdownItem"][];
            access_prefix: components["schemas"]["BreakdownItem"][];
        };
        HeatmapCell: {
            /** @description 0 = Chủ nhật */
            weekday: number;
            hour: number;
            /** Format: int64 */
            clicks: number;
        };
        TopItem: {
            /** @description Khoá điều hướng (username / mã chiến dịch / ctv_ref / mã link) */
            key: string;
            label: string;
            /** Format: int64 */
            clicks: number;
            /** Format: int64 */
            unique_clicks: number;
            /** Format: int64 */
            suspicious_clicks?: number;
            owner?: string;
        };
        ReportSummary: {
            kpis: components["schemas"]["Kpis"];
            series: components["schemas"]["Series"];
            breakdowns: components["schemas"]["Breakdowns"];
            heatmap: components["schemas"]["HeatmapCell"][];
        };
        OverviewReport: {
            summary: components["schemas"]["ReportSummary"];
            top_accounts: components["schemas"]["TopItem"][];
            top_campaigns: components["schemas"]["TopItem"][];
            top_ctvs: components["schemas"]["TopItem"][];
            top_links: components["schemas"]["TopItem"][];
        };
        AccountRow: {
            username: string;
            metrics: components["schemas"]["Metrics"];
            /** Format: double */
            change_clicks?: number | null;
        };
        AccountRowPage: {
            items: components["schemas"]["AccountRow"][];
            total: number;
            page: number;
            page_size: number;
            totals: components["schemas"]["Metrics"];
        };
        CampaignRow: {
            /** @description Rỗng = link không gắn chiến dịch */
            code: string;
            name: string;
            metrics: components["schemas"]["Metrics"];
            /**
             * Format: int64
             * @description Số CTV có hoạt động (click hoặc link mới) trong kỳ
             */
            ctv_count: number;
            /**
             * Format: date
             * @description Ngày đầu tiên có hoạt động trong kỳ
             */
            first_date?: string;
            /** Format: date */
            last_click_date?: string;
            /** Format: double */
            change_clicks?: number | null;
        };
        CampaignRowPage: {
            items: components["schemas"]["CampaignRow"][];
            total: number;
            page: number;
            page_size: number;
            totals: components["schemas"]["Metrics"];
        };
        CTVRankRow: {
            /** @description Mã tham chiếu mờ (dùng trên URL); rỗng = chưa định danh */
            ctv_ref: string;
            /** @description SĐT đã che (đủ với admin) / hash */
            ctv_display: string;
            name?: string;
            rank: number;
            metrics: components["schemas"]["Metrics"];
        };
        AccountReport: {
            username: string;
            summary: components["schemas"]["ReportSummary"];
            campaigns: components["schemas"]["CampaignRow"][];
            top_ctvs: components["schemas"]["TopItem"][];
            top_links: components["schemas"]["TopItem"][];
        };
        CampaignReport: {
            code: string;
            name: string;
            summary: components["schemas"]["ReportSummary"];
            ctv_ranking: components["schemas"]["CTVRankRow"][];
            top_links: components["schemas"]["TopItem"][];
        };
        CampaignCompareItem: {
            code: string;
            name: string;
            metrics: components["schemas"]["Metrics"];
            series: components["schemas"]["SeriesPoint"][];
        };
        CampaignCompare: {
            period: components["schemas"]["Period"];
            granularity: components["schemas"]["Granularity"];
            items: components["schemas"]["CampaignCompareItem"][];
        };
        CTVRankPage: {
            items: components["schemas"]["CTVRankRow"][];
            total: number;
            page: number;
            page_size: number;
            totals: components["schemas"]["Metrics"];
        };
        CTVLookupItem: {
            ctv_ref: string;
            ctv_display: string;
            name?: string;
            owner: string;
            /** Format: int64 */
            links: number;
            /**
             * Format: int64
             * @description Tổng click toàn thời gian (links.clicks)
             */
            clicks_total: number;
            /** Format: date-time */
            first_link_at: string;
            /** Format: date-time */
            last_link_at: string;
            sample_links?: components["schemas"]["LinkInfo"][];
        };
        CTVLookup: {
            query: string;
            /** @description Giá trị sau chuẩn hoá (SĐT về 0xxxxxxxxx) — đã che nếu không phải admin */
            normalized: string;
            items: components["schemas"]["CTVLookupItem"][];
        };
        LinkInfo: {
            code: string;
            short_url: string;
            long_url: string;
            dest_host?: string;
            owner: string;
            campaign_code: string;
            ctv_ref: string;
            ctv_display: string;
            prefix: string;
            /** @enum {string} */
            status: "active" | "disabled" | "deleted";
            is_custom?: boolean;
            api_version?: string;
            /** Format: date-time */
            created_at: string;
        };
        LinkRow: {
            link: components["schemas"]["LinkInfo"];
            /** Format: int64 */
            clicks: number;
            /** Format: int64 */
            unique_clicks: number;
            /** Format: int64 */
            suspicious_clicks?: number;
            /** Format: int64 */
            previous_clicks?: number;
            /** Format: double */
            growth?: number | null;
            /** Format: date */
            last_click_date?: string;
        };
        LinkRowPage: {
            items: components["schemas"]["LinkRow"][];
            total: number;
            page: number;
            page_size: number;
        };
        UnidentifiedReport: {
            metrics: components["schemas"]["Metrics"];
            /**
             * Format: double
             * @description Tỉ trọng click chưa định danh trên tổng click cùng phạm vi
             */
            share_of_clicks?: number;
            links: components["schemas"]["LinkRowPage"];
        };
        CTVReport: {
            ctv_ref: string;
            ctv_display: string;
            name?: string;
            owners?: string[];
            summary: components["schemas"]["ReportSummary"];
            campaigns: components["schemas"]["CampaignRow"][];
            links: components["schemas"]["LinkRow"][];
            alerts: components["schemas"]["Alert"][];
        };
        Alert: {
            /** @enum {string} */
            level: "info" | "warning" | "critical";
            code: string;
            message: string;
        };
        LinkReport: {
            link: components["schemas"]["LinkInfo"];
            summary: components["schemas"]["ReportSummary"];
            recent_clicks: components["schemas"]["ClickRow"][];
        };
        /** @description Điều kiện 1 tiêu chí — OR giữa các giá trị; exclude = NOT */
        Criterion: {
            values: string[];
            /** @default false */
            exclude?: boolean;
        };
        ParamCondition: {
            key: string;
            /** @enum {string} */
            op: "eq" | "in" | "contains" | "exists" | "not_exists";
            values?: string[];
            /** @default false */
            exclude?: boolean;
        };
        /** @description Tiêu chí lọc click (§4.1a). AND giữa các tiêu chí, OR trong cùng tiêu chí. */
        ClickFilters: {
            links?: components["schemas"]["Criterion"];
            access_prefix?: components["schemas"]["Criterion"];
            api_version?: components["schemas"]["Criterion"];
            dest_host?: components["schemas"]["Criterion"];
            device?: components["schemas"]["Criterion"];
            os?: components["schemas"]["Criterion"];
            browser?: components["schemas"]["Criterion"];
            source_group?: components["schemas"]["Criterion"];
            referer_host?: components["schemas"]["Criterion"];
            country?: components["schemas"]["Criterion"];
            province?: components["schemas"]["Criterion"];
            ip?: components["schemas"]["Criterion"];
            /** @description 0 = Chủ nhật */
            weekdays?: number[];
            hour_from?: number;
            /** @description Gồm cả giờ này; hour_from > hour_to = qua nửa đêm */
            hour_to?: number;
            is_custom?: boolean;
            /** Format: date */
            link_created_from?: string;
            /** Format: date */
            link_created_to?: string;
            /**
             * @default all
             * @enum {string}
             */
            quality?: "valid" | "bot" | "suspicious" | "all";
            /**
             * @default all
             * @enum {string}
             */
            visit?: "all" | "first" | "repeat";
            /**
             * @default any
             * @enum {string}
             */
            campaign_presence?: "any" | "with" | "without";
            /**
             * @default any
             * @enum {string}
             */
            ctv_presence?: "any" | "identified" | "unidentified";
            params?: components["schemas"]["ParamCondition"][];
        };
        ClickRow: {
            /** Format: date-time */
            ts: string;
            code: string;
            prefix?: string;
            access_prefix?: string;
            long_url?: string;
            owner: string;
            campaign_code?: string;
            ctv_ref?: string;
            ctv_display?: string;
            device: string;
            os: string;
            browser: string;
            source_group: string;
            referer_host?: string;
            country: string;
            province?: string;
            /** @description Che với vai trò khác admin */
            ip: string;
            is_bot: boolean;
            is_suspicious: boolean;
            is_repeat: boolean;
        };
        ClickPage: {
            items: components["schemas"]["ClickRow"][];
            /** @description Rỗng = hết dữ liệu */
            next_cursor?: string;
        };
        ExplorerQuery: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            account?: string[];
            campaign?: string[];
            ctv?: string[];
            prefix?: string[];
            filters?: components["schemas"]["ClickFilters"];
            /**
             * @description Chiều nhóm: account, campaign, ctv, link, link_prefix, access_prefix, api_version, dest_host,
             *     device, os, browser, source_group, referer_host, country, province, day, week, month, hour, weekday,
             *     param.<key> (tham số URL đang theo dõi, không phải PII)
             */
            group_by: string[];
            /** @default false */
            compare?: boolean;
            /**
             * @default clicks
             * @enum {string}
             */
            sort_by?: "clicks" | "unique_clicks" | "bot_clicks" | "suspicious_clicks" | "active_links" | "clicks_per_link" | "key";
            order?: components["schemas"]["SortOrder"];
            /**
             * @description Top N nhóm, phần còn lại gộp "khác"
             * @default 100
             */
            limit?: number;
        };
        ExplorerMetrics: {
            /** Format: int64 */
            clicks: number;
            /** Format: int64 */
            unique_clicks: number;
            /** Format: int64 */
            bot_clicks: number;
            /** Format: int64 */
            suspicious_clicks: number;
            /** Format: int64 */
            active_links: number;
            /** Format: double */
            clicks_per_link: number;
            /** Format: date-time */
            first_click_at?: string;
            /** Format: date-time */
            last_click_at?: string;
        };
        ExplorerTotals: {
            metrics: components["schemas"]["ExplorerMetrics"];
            /**
             * Format: int64
             * @description Số tài khoản có click
             */
            accounts: number;
            /**
             * Format: int64
             * @description Số CTV (đã định danh) có click
             */
            ctvs: number;
        };
        ExplorerKey: {
            dim: string;
            /** @description Giá trị dùng để lọc / drill-down (vd ctv_ref, mã link) */
            value: string;
            /** @description Nhãn hiển thị (SĐT đã che…) */
            label: string;
        };
        ExplorerRow: {
            keys: components["schemas"]["ExplorerKey"][];
            metrics: components["schemas"]["ExplorerMetrics"];
            /**
             * Format: double
             * @description clicks / tổng clicks
             */
            share: number;
            /** Format: int64 */
            previous_clicks?: number;
            /** Format: double */
            change_clicks?: number | null;
        };
        ExplorerResult: {
            /**
             * @description stats = số liệu tổng hợp (≤ 12 tháng); clicks = click thô (≤ 3 tháng)
             * @enum {string}
             */
            source: "stats" | "clicks";
            period: components["schemas"]["Period"];
            group_by: string[];
            totals: components["schemas"]["ExplorerTotals"];
            previous_totals?: components["schemas"]["ExplorerTotals"];
            rows: components["schemas"]["ExplorerRow"][];
            other?: components["schemas"]["ExplorerRow"];
            /** @description true = có nhóm bị gộp vào "khác" */
            truncated: boolean;
            group_count?: number;
        };
        FacetItem: {
            value: string;
            label: string;
            /** Format: int64 */
            clicks: number;
        };
        FacetList: {
            field: string;
            items: components["schemas"]["FacetItem"][];
        };
        ParamSummary: {
            key: string;
            label: string;
            /** @enum {string} */
            status: "active" | "high_cardinality" | "disabled";
            /**
             * Format: int64
             * @description Số giá trị khác nhau có click trong kỳ
             */
            values: number;
            /**
             * Format: int64
             * @description Số link mang tham số (trong phạm vi)
             */
            links: number;
            /** Format: int64 */
            clicks: number;
            /**
             * Format: date
             * @description Số liệu chỉ có từ ngày này (backfill)
             */
            tracked_since?: string;
        };
        ParamSummaryList: {
            items: components["schemas"]["ParamSummary"][];
        };
        ParamValueRow: {
            value: string;
            metrics: components["schemas"]["Metrics"];
            /**
             * Format: int64
             * @description Số link có click mang giá trị này
             */
            links: number;
            /** Format: int64 */
            accounts: number;
            /** Format: int64 */
            campaigns: number;
            /** Format: double */
            share: number;
            /** Format: double */
            change_clicks?: number | null;
        };
        ParamReport: {
            param: components["schemas"]["ParamSummary"];
            rows: components["schemas"]["ParamValueRow"][];
            total: number;
            page: number;
            page_size: number;
            /** @description Timeline top 5 giá trị */
            top_series: {
                value: string;
                points: components["schemas"]["SeriesPoint"][];
            }[];
            warnings: components["schemas"]["Alert"][];
        };
        SavedReportInput: {
            name: string;
            description?: string;
            /** @enum {string} */
            kind: "explorer" | "clicks";
            /** @description Trạng thái màn hình (bộ lọc, group_by, biểu đồ…) — chạy lại theo phạm vi của người mở */
            query: {
                [key: string]: unknown;
            };
        };
        SavedReport: {
            id: string;
            name: string;
            description?: string;
            /** @enum {string} */
            kind: "explorer" | "clicks";
            query: {
                [key: string]: unknown;
            };
            owner: string;
            is_mine: boolean;
            share_token?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SavedReportList: {
            items: components["schemas"]["SavedReport"][];
        };
    };
    responses: {
        /** @description Lỗi (RFC 9457 problem+json) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
        Q: string;
        Limit: number;
        /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
        Account: string[];
        /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
        From: string;
        /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
        To: string;
        /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
        Campaign: string[];
        /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
        Ctv: string[];
        /** @description Prefix cấp cho link (`sale`, `lm`…) */
        Prefix: string[];
        /** @description So với kỳ trước liền kề (cùng số ngày) */
        Compare: boolean;
        Granularity: components["schemas"]["Granularity"];
        SavedId: string;
        Page: number;
        PageSize: number;
        /** @description Trường sắp xếp (vd `clicks`, `unique_clicks`, `new_links`, `username`, `code`) */
        Sort: string;
        Order: components["schemas"]["SortOrder"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Đăng nhập thành công */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            423: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Cặp token mới */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Đã đăng xuất */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listFilterAccounts: {
        parameters: {
            query?: {
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountOptionList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    listFilterCampaigns: {
        parameters: {
            query?: {
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                limit?: components["parameters"]["Limit"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOptionList"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listFilterPrefixes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefixOptionList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getOverview: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listAccountReports: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description Trường sắp xếp (vd `clicks`, `unique_clicks`, `new_links`, `username`, `code`) */
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRowPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getAccountReport: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listCampaignReports: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description Trường sắp xếp (vd `clicks`, `unique_clicks`, `new_links`, `username`, `code`) */
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRowPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    compareCampaigns: {
        parameters: {
            query: {
                codes: string[];
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignCompare"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getCampaignReport: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                /** @description Mã chiến dịch; `-` = link không gắn chiến dịch */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listCtvReports: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description Trường sắp xếp (vd `clicks`, `unique_clicks`, `new_links`, `username`, `code`) */
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CTVRankPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    lookupCtv: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CTVLookup"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getUnidentifiedCtv: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidentifiedReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getCtvReport: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CTVReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listTopLinks: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                mode?: "clicks" | "growth" | "dead";
                /** @description Với mode=dead — số ngày gần nhất không có click (tính đến `to`) */
                dead_days?: number;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkRowPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getLinkReport: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getLinkQrcode: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listClicks: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description CTV — SĐT (mọi định dạng, tự chuẩn hoá), hash hoặc ctv_ref; `-` = chưa định danh */
                ctv?: components["parameters"]["Ctv"];
                /** @description Prefix cấp cho link (`sale`, `lm`…) */
                prefix?: components["parameters"]["Prefix"];
                /** @description Tiêu chí lọc chi tiết (JSON ClickFilters) — dùng cho drill-down từ Click Explorer */
                filters?: string;
                cursor?: string;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClickPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    queryClicks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplorerQuery"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplorerResult"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            504: components["responses"]["Problem"];
        };
    };
    getClickFacets: {
        parameters: {
            query: {
                field: string;
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    listParamReports: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamSummaryList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getParamReport: {
        parameters: {
            query: {
                /** @description Ngày bắt đầu (gồm), theo ngày lịch Asia/Ho_Chi_Minh */
                from: components["parameters"]["From"];
                /** @description Ngày kết thúc (gồm trọn ngày). Số liệu tổng hợp tối đa 12 tháng. */
                to: components["parameters"]["To"];
                /** @description Lọc theo tài khoản (lặp lại tham số cho nhiều giá trị). Ngoài phạm vi → 403. */
                account?: components["parameters"]["Account"];
                /** @description Mã chiến dịch (lặp lại cho nhiều giá trị; `-` = không gắn chiến dịch) */
                campaign?: components["parameters"]["Campaign"];
                /** @description So với kỳ trước liền kề (cùng số ngày) */
                compare?: components["parameters"]["Compare"];
                granularity?: components["parameters"]["Granularity"];
                /** @description Tìm theo chuỗi con (không phân biệt hoa thường) */
                q?: components["parameters"]["Q"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
                /** @description Trường sắp xếp (vd `clicks`, `unique_clicks`, `new_links`, `username`, `code`) */
                sort?: components["parameters"]["Sort"];
                order?: components["parameters"]["Order"];
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParamReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listSavedReports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReportList"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createSavedReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedReportInput"];
            };
        };
        responses: {
            /** @description Đã lưu */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
        };
    };
    getSharedReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    getSavedReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SavedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    deleteSavedReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SavedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xoá */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    updateSavedReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SavedId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedReportInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    shareSavedReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SavedId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    enabled: boolean;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedReport"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
}
